version: "3"

services:

    appCore:
        image: node:11
        restart: always
        ports:
            - "3000:3000"
            - "35729:35729"
        working_dir: /app
        volumes:
            - ./app-core:/app
        entrypoint: ["npm", "start"]
#        links:
#            - api
        networks:
            - appnetwork
    
    aspnet-template:
        build:
            context: ./gcf-template-webservice-aspnet
            dockerfile: ./gcf-template-webservice-aspnet/Dockerfile
        ports:
            - "8080:80"
        networks:
            - appnetwork
            
#    api:
#        image: webapp-api
#        restart: always
#        ports:
#            - "9000:9000"
#        volumes:
#            - ./api:/api
#            - /api/node_modules
#        depends_on:
#            - mongodb
#        networks:
#            - appnetwork
#    mongodb:
#        image: mongo
#        restart: always
#        container_name: mongodb
#        volumes:
#            - ./data-node:/data/db
#        ports:
#            - 27017:27017
#        command: mongod --noauth --smallfiles
#        networks:
#            - appnetwork
networks:
    appnetwork:
        driver: bridge
