version: "3"

services:

    appCore:
        image: node:11
        container_name: app-core
        restart: always
        ports:
            - "3000:3000"
            - "35729:35729"
        working_dir: /app
        volumes:
            - ./app-core:/app
        entrypoint: ["npm", "start"]
#        links:
#            - api
        networks:
            - appnetwork
    
    aspnet-template:
        container_name: aspnet-template
        build:
            context: ./gcf-template-webservice-aspnet
            dockerfile: ./gcf-template-webservice-aspnet/Dockerfile
        ports:
            - "53415:80"
        networks:
            - appnetwork
            
#    api:
#        image: webapp-api
#        restart: always
#        ports:
#            - "9000:9000"
#        volumes:
#            - ./api:/api
#            - /api/node_modules
#        depends_on:
#            - mongodb
#        networks:
#            - appnetwork

# CONFIG DB
# START APP_DB:ORACLE
    oracledb:
        image: carloscastillo/rgt-oracle-xe-11g:latest
        container_name: oracle-xe-11g
        ports:
            - "15080:8080"
            - "1521:1521"
        environment:
            - processes=200
            - SCHEMAS=APPS
            - BATCH_PARAMS=World
        volumes:
            - ./resources/db_oracle/data:/u01/app/oracle
        networks:
            - appnetwork
            
# END APP_DB:ORACLE

# START APP_DB:MONGODB

#    mongodb:
#        image: mongo
#        restart: always
#        container_name: mongodb
#        volumes:
#            - ./data-node:/data/db
#        ports:
#            - 27017:27017
#        command: mongod --noauth --smallfiles
#        networks:
#            - appnetwork

# END APP_DB:MONGODB

    
# CONFIG STS

# START APP_STS:KEYCLOAK

    keycloak:
      image: jboss/keycloak
      container_name: keycloak
      environment:
        ## ORACLE DB
        #DB_VENDOR: ORACLE
        #DB_ADDR: oracledb
        #DB_PORT: 1521
        #DB_DATABASE: XE
        #DB_USER: SYSTEM
        #DB_PASSWORD: oracle
        
        KEYCLOAK_USER: kcadmin
        KEYCLOAK_PASSWORD: P@ssw0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      #volumes:
      #  - ./resources/jdbc-oracle/11g-release2-11.2.0.4:/opt/jboss/keycloak/modules/system/layers/base/com/oracle/jdbc/main/driver
      networks:
        - appnetwork
      ports:
        - 8080:8080
      depends_on:
        - oracledb
        
# END APP_STS:KEYCLOAK


# START ELASTICSEARCH 7.0

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
        container_name: es01
        environment:
            - node.name=es01
            #- discovery.seed_hosts=es02
            #- cluster.initial_master_nodes=es01,es02
            - cluster.initial_master_nodes=es01
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./resources/elk/es01_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - appnetwork
    
networks:
    appnetwork:
        driver: bridge
